### ISSUE TITLE
 [3.1.0-5] Login problem

### ISSUE THREAD

**Issue by BeReal86** [XGProyect/XG-Proyect-v3.x.x#385] opened 2020-10-09 17:02 UTC
when trying to login to the site via http://. It ends up negatively. Login via https:// is done smoothly.

Hosting test
Php 7.3.21

**Comment by duhow** [comment] 2020-10-10 13:54
What's that "negatively" refering to? May it be fixed by #381 ?

**Comment by BeReal86** [comment] 2020-10-10 14:03
I haven't tried that. I'm checking now.

**Comment by BeReal86** [comment] 2020-10-10 14:16
I tried but it doesn't work. Not logging in with http. And there is a problem with register. Have @LucasKovacs  check it out. we try again.

**Comment by duhow** [comment] 2020-10-10 14:20
Can you provide some request logs to trace where is it trying to do HTTP GET/POST ?
If this is an issue with hosting, it may be because of forcing HTTPS - HTTP Strict Transport Security (HSTS) ?

**Comment by LucasKovacs** [comment] 2020-10-20 05:40
@BeReal86 we need more information to resolve this. Locally I use http and it does not cause any issue

**Comment by BeReal86** [comment] 2020-10-20 05:52
Yes I know there is no problem in local server.
But there is a problem with a normal hosting server. I made a little video for you. This explains the problem better.

https://drive.google.com/file/d/1Slor1FWF7YLrkZ53Sf5ICIVjwbghUzVQ/view?usp=sharing

**Comment by duhow** [comment] 2020-10-20 07:32
![image](https://user-images.githubusercontent.com/1145001/96554208-86368580-12b6-11eb-8431-680b3d5c6457.png)
![image](https://user-images.githubusercontent.com/1145001/96554619-107ee980-12b7-11eb-9f48-04531968e7c5.png)

Problem is just cookies and modern browsers.
Once you reach a secure site, browser won't update the same cookie (`PHPSESSID`) in a insecure connection
Note that latest Chrome version would request to move to a secure website with [Upgrade-Insecure-Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade-Insecure-Requests) .

**Comment by duhow** [comment] 2020-10-20 07:37
Not a bug itself for XGProyect, but if you want to fix it, you can:
- Configure host and redirect all requests to HTTPS
- In XGProyect config, add a config item:
- [ ] Use HTTPS

```php
$using_ssl = (isset($_SERVER['HTTPS']) && !empty($_SERVER['HTTPS']) ? true : false;
if (!$using_ssl) {
    header("Location: https://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
}
```

**Closed** 2020-10-25 13:21 UTC
Labels: Bug, Not a bug
