### ISSUE TITLE
2 bugs found on installation process

### ISSUE THREAD

**Issue by jascaldeira** [XGProyect/XG-Proyect-v3.x.x#372] opened 2020-08-25 10:20 UTC
**Describe the bug**
Bug 1:
After upload, i try to open the url
and it redirects me to 
[DOMAIN]install
and not
[DOMAIN]/install
( / was missing)

Bug 2:
After open the correct URL, it says the "views/general/simple_footer" does not exists...
and in fact... i didnt found that file... only the "footer" not "simple_footer"

**To Reproduce**
Just upload the latest release (i think still a beta)
 
 **Server (please complete the following information):**
 - php 7.4.8

**Comment by BeReal86** [comment] 2020-08-25 11:15
Hello @jascaldeira , Thank you for your feedback.

Which version exactly did you install and where this experiment occurred. You can also add pictures to explain the errors that occur better. So you can help us better. If you downloaded version 3.1 and tried it, it is not stable at the moment. There are a few problems.

**Comment by FGServers** [comment] 2020-08-25 17:15
1. First bug: if it happens when you put the game inside a folder. (Confirmed)
2. Second bug it's filled with the last commit

**Comment by BeReal86** [comment] 2020-08-25 17:23
![resim](https://user-images.githubusercontent.com/16218107/91206982-b75c6480-e710-11ea-87ef-5f471549e97b.png)
![resim](https://user-images.githubusercontent.com/16218107/91207006-c04d3600-e710-11ea-90c3-d4be160742cd.png)

**Comment by FGServers** [comment] 2020-08-25 19:19
> I did not have any problem. He went straight to the download page.
> ![resim](https://user-images.githubusercontent.com/16218107/91206982-b75c6480-e710-11ea-87ef-5f471549e97b.png)
> ![resim](https://user-images.githubusercontent.com/16218107/91207006-c04d3600-e710-11ea-90c3-d4be160742cd.png)

change languaje select

**Comment by BeReal86** [comment] 2020-08-25 19:52
yes I get an error when I select a language. But this is only on localhost
![resim](https://user-images.githubusercontent.com/16218107/91220917-94887b00-e725-11ea-8126-8d24ef247df7.png)

**Comment by LucasKovacs** [comment] 2020-08-30 09:01
I believe that this bug is due to the game not being properly installed.

All the content of the upload folder must be inside of a folder in your hosting. If the reporter provides more information, he can re open it. But in the meantime I will close it.

**Comment by BeReal86** [comment] 2020-08-30 09:17
The problem with the language selection is only on the local server.  I have not encountered such a problem in hosting.

**Comment by LucasKovacs** [comment] 2020-08-30 10:06
@BeReal86 @FGServers I decided to investigate a little bit further, and was able to reproduce the language issue while on a subfolder, and also added support to it.

Please verify and let me know 😎

**Closed** 2020-08-30 10:17 UTC
Labels: Bug, Fixed, Re-Opened

**Comment by BeReal86** [comment] 2020-08-30 10:41
works smoothly
local and hosting
![resim](https://user-images.githubusercontent.com/16218107/91656841-c2264900-eac4-11ea-82db-06943cde81e8.png)
![resim](https://user-images.githubusercontent.com/16218107/91656850-d702dc80-eac4-11ea-8ef7-5e7c7ea83eb3.png)

**Comment by FGServers** [comment] 2020-08-30 15:38
Funciona perfecto lo del seleccionar idioma
